/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DocsRouteImport } from './routes/documentation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ConnectIndexRouteImport } from './routes/connect/index'
import { Route as BillingIndexRouteImport } from './routes/billing/index'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as BillingPortalRouteImport } from './routes/billing/portal'
import { Route as BillingCanceledRouteImport } from './routes/billing/canceled'
import { Route as AuthVerifyEmailIndexRouteImport } from './routes/auth/verify-email/index'
import { Route as AuthResetIndexRouteImport } from './routes/auth/reset/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectIndexRoute = ConnectIndexRouteImport.update({
  id: '/connect/',
  path: '/connect/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPortalRoute = BillingPortalRouteImport.update({
  id: '/billing/portal',
  path: '/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCanceledRoute = BillingCanceledRouteImport.update({
  id: '/billing/canceled',
  path: '/billing/canceled',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailIndexRoute = AuthVerifyEmailIndexRouteImport.update({
  id: '/auth/verify-email/',
  path: '/auth/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetIndexRoute = AuthResetIndexRouteImport.update({
  id: '/auth/reset/',
  path: '/auth/reset/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/billing/canceled': typeof BillingCanceledRoute
  '/billing/portal': typeof BillingPortalRoute
  '/billing/success': typeof BillingSuccessRoute
  '/billing': typeof BillingIndexRoute
  '/connect': typeof ConnectIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset': typeof AuthResetIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/billing/canceled': typeof BillingCanceledRoute
  '/billing/portal': typeof BillingPortalRoute
  '/billing/success': typeof BillingSuccessRoute
  '/billing': typeof BillingIndexRoute
  '/connect': typeof ConnectIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset': typeof AuthResetIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documentation': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/billing/canceled': typeof BillingCanceledRoute
  '/billing/portal': typeof BillingPortalRoute
  '/billing/success': typeof BillingSuccessRoute
  '/billing/': typeof BillingIndexRoute
  '/connect/': typeof ConnectIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset/': typeof AuthResetIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentation'
    | '/pricing'
    | '/billing/canceled'
    | '/billing/portal'
    | '/billing/success'
    | '/billing'
    | '/connect'
    | '/projects'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documentation'
    | '/pricing'
    | '/billing/canceled'
    | '/billing/portal'
    | '/billing/success'
    | '/billing'
    | '/connect'
    | '/projects'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify-email'
  id:
    | '__root__'
    | '/'
    | '/documentation'
    | '/pricing'
    | '/billing/canceled'
    | '/billing/portal'
    | '/billing/success'
    | '/billing/'
    | '/connect/'
    | '/projects/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/reset/'
    | '/auth/verify-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  PricingRoute: typeof PricingRoute
  BillingCanceledRoute: typeof BillingCanceledRoute
  BillingPortalRoute: typeof BillingPortalRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  BillingIndexRoute: typeof BillingIndexRoute
  ConnectIndexRoute: typeof ConnectIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetIndexRoute: typeof AuthResetIndexRoute
  AuthVerifyEmailIndexRoute: typeof AuthVerifyEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/': {
      id: '/connect/'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/portal': {
      id: '/billing/portal'
      path: '/billing/portal'
      fullPath: '/billing/portal'
      preLoaderRoute: typeof BillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/canceled': {
      id: '/billing/canceled'
      path: '/billing/canceled'
      fullPath: '/billing/canceled'
      preLoaderRoute: typeof BillingCanceledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email/': {
      id: '/auth/verify-email/'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset/': {
      id: '/auth/reset/'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  PricingRoute: PricingRoute,
  BillingCanceledRoute: BillingCanceledRoute,
  BillingPortalRoute: BillingPortalRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  BillingIndexRoute: BillingIndexRoute,
  ConnectIndexRoute: ConnectIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetIndexRoute: AuthResetIndexRoute,
  AuthVerifyEmailIndexRoute: AuthVerifyEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
